2025-05-30 00:19:55,475 ERROR: MongoDB connection error: your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms), Timeout: 5.0s, Topology Description: <TopologyDescription id: 6838892627276637f04f6234, topology_type: Unknown, servers: [<ServerDescription ('your_mongodb_connection_string_here', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms)')>]> [in /Users/lixinyu/Desktop/web/utils/db.py:44]
2025-05-30 00:19:55,477 ERROR: MongoDB connection not available for GridFS [in /Users/lixinyu/Desktop/web/utils/gridfs_utils.py:45]
2025-05-30 00:21:26,551 INFO: Application started [in /Users/lixinyu/Desktop/web/app.py:47]
2025-05-30 00:21:31,607 ERROR: MongoDB connection error: localhost:27017: [Errno 61] Connection refused (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms), Timeout: 5.0s, Topology Description: <TopologyDescription id: 683889866e8fa8d0df35abcb, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms)')>]> [in /Users/lixinyu/Desktop/web/utils/db.py:44]
2025-05-30 00:21:36,674 ERROR: MongoDB connection error: localhost:27017: [Errno 61] Connection refused (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms), Timeout: 5.0s, Topology Description: <TopologyDescription id: 6838898b6e8fa8d0df35abcc, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms)')>]> [in /Users/lixinyu/Desktop/web/utils/db.py:44]
2025-05-30 00:21:36,674 ERROR: MongoDB connection not available for GridFS [in /Users/lixinyu/Desktop/web/utils/gridfs_utils.py:45]
2025-05-30 00:23:30,238 INFO: Application started [in /Users/lixinyu/Desktop/web/app.py:47]
2025-05-30 00:23:35,302 ERROR: MongoDB connection error: your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms), Timeout: 5.0s, Topology Description: <TopologyDescription id: 68388a0205d3ec4b29503fb6, topology_type: Unknown, servers: [<ServerDescription ('your_mongodb_connection_string_here', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms)')>]> [in /Users/lixinyu/Desktop/web/utils/db.py:44]
2025-05-30 00:23:40,382 ERROR: MongoDB connection error: your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms), Timeout: 5.0s, Topology Description: <TopologyDescription id: 68388a0705d3ec4b29503fb7, topology_type: Unknown, servers: [<ServerDescription ('your_mongodb_connection_string_here', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms)')>]> [in /Users/lixinyu/Desktop/web/utils/db.py:44]
2025-05-30 00:23:40,382 ERROR: MongoDB connection not available for GridFS [in /Users/lixinyu/Desktop/web/utils/gridfs_utils.py:45]
2025-05-30 00:23:43,665 INFO: Application started [in /Users/lixinyu/Desktop/web/app.py:47]
2025-05-30 00:23:48,736 ERROR: MongoDB connection error: your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms), Timeout: 5.0s, Topology Description: <TopologyDescription id: 68388a0f5cfed464f8831452, topology_type: Unknown, servers: [<ServerDescription ('your_mongodb_connection_string_here', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms)')>]> [in /Users/lixinyu/Desktop/web/utils/db.py:44]
2025-05-30 00:23:53,818 ERROR: MongoDB connection error: your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms), Timeout: 5.0s, Topology Description: <TopologyDescription id: 68388a145cfed464f8831453, topology_type: Unknown, servers: [<ServerDescription ('your_mongodb_connection_string_here', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms)')>]> [in /Users/lixinyu/Desktop/web/utils/db.py:44]
2025-05-30 00:23:53,818 ERROR: MongoDB connection not available for GridFS [in /Users/lixinyu/Desktop/web/utils/gridfs_utils.py:45]
2025-05-30 00:24:05,176 INFO: Application started [in /Users/lixinyu/Desktop/web/app.py:47]
2025-05-30 00:24:10,244 ERROR: MongoDB connection error: your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms), Timeout: 5.0s, Topology Description: <TopologyDescription id: 68388a25a0044c98e1cd581a, topology_type: Unknown, servers: [<ServerDescription ('your_mongodb_connection_string_here', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms)')>]> [in /Users/lixinyu/Desktop/web/utils/db.py:44]
2025-05-30 00:24:15,313 ERROR: MongoDB connection error: your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms), Timeout: 5.0s, Topology Description: <TopologyDescription id: 68388a2aa0044c98e1cd581b, topology_type: Unknown, servers: [<ServerDescription ('your_mongodb_connection_string_here', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms)')>]> [in /Users/lixinyu/Desktop/web/utils/db.py:44]
2025-05-30 00:24:15,314 ERROR: MongoDB connection not available for GridFS [in /Users/lixinyu/Desktop/web/utils/gridfs_utils.py:45]
2025-05-30 00:24:21,625 INFO: Application started [in /Users/lixinyu/Desktop/web/app.py:47]
2025-05-30 00:24:26,696 ERROR: MongoDB connection error: your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms), Timeout: 5.0s, Topology Description: <TopologyDescription id: 68388a35ecae75aed36246e6, topology_type: Unknown, servers: [<ServerDescription ('your_mongodb_connection_string_here', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms)')>]> [in /Users/lixinyu/Desktop/web/utils/db.py:44]
2025-05-30 00:24:31,765 ERROR: MongoDB connection error: your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms), Timeout: 5.0s, Topology Description: <TopologyDescription id: 68388a3aecae75aed36246e7, topology_type: Unknown, servers: [<ServerDescription ('your_mongodb_connection_string_here', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms)')>]> [in /Users/lixinyu/Desktop/web/utils/db.py:44]
2025-05-30 00:24:31,766 ERROR: MongoDB connection not available for GridFS [in /Users/lixinyu/Desktop/web/utils/gridfs_utils.py:45]
2025-05-30 00:24:41,046 INFO: Application started [in /Users/lixinyu/Desktop/web/app.py:47]
2025-05-30 00:24:46,126 ERROR: MongoDB connection error: your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms), Timeout: 5.0s, Topology Description: <TopologyDescription id: 68388a499bc280b47d4927e6, topology_type: Unknown, servers: [<ServerDescription ('your_mongodb_connection_string_here', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms)')>]> [in /Users/lixinyu/Desktop/web/utils/db.py:44]
2025-05-30 00:24:51,193 ERROR: MongoDB connection error: your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms), Timeout: 5.0s, Topology Description: <TopologyDescription id: 68388a4e9bc280b47d4927e7, topology_type: Unknown, servers: [<ServerDescription ('your_mongodb_connection_string_here', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('your_mongodb_connection_string_here:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 5000.0ms, connectTimeoutMS: 5000.0ms)')>]> [in /Users/lixinyu/Desktop/web/utils/db.py:44]
